language: node_js
sudo: false
node_js:
  - '6'
env:
  global:
    - CXX=g++-4.8
addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install --global npm
  - npm install -g gulp
  - npm install -g karma
  - npm install